### PR TITLE
upgrade data to version 2023b from  evansiroky/timezone-boundary-builder

### PR DESCRIPTION
**Pull request by juarezr**
### Changes

- Upgraded data to version [2023b](https://github.com/evansiroky/timezone-boundary-builder/releases/tag/2023b)
- Updated version in the readme and docs

### CODE REVIEW

**Review by RomanIakovlev — APPROVED** [review]
Looks good, thanks!

**Comment by RomanIakovlev** [comment]
P.S. This PR will only produce a snapshot build. For a release to happen, you should set the version to a non-SNAPSHOT. This is typically done in a couple PRs like this:

1. Bump the data version and set code version to non-SNAPSHOT, e.g. `2023b.18`
2. After first PR is merged, bump the code version to next SNAPSHOT, e.g. `2023b.19-SNAPSHOT`.

You can either add a commit with setting the code version to non-SNAPSHOT into this PR or create another one.

**Comment by juarezr** [comment]
> You can either add a commit with setting the code version to non-SNAPSHOT into this PR or create another one.

Done.

Also, I have been using another similar trick to issue releases:

1. Use trigger [on release](https://github.com/petl-developers/petl/blob/e829532e2ed350d00b96680d2d6774dec4a7f2e0/.github/workflows/publish-release.yml#L4) instead of `on push` in the `master` branch.
2. Use the [github.event.release.tag_name](https://github.com/petl-developers/petl/blob/e829532e2ed350d00b96680d2d6774dec4a7f2e0/.github/workflows/publish-release.yml#L28) value from the GitHub workflow as tag name for the release.
3. Issue the release directly in the GitHub [Draft New Release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) page each time I have all commits done in the main/master branch and everything ready for release.

It helps me decouple the release from PRs and the `main` branch and communicate the changes in the release to the users/developers who are using my library.

**Comment by juarezr** [comment]
@RomanIakovlev ,

Do you know why the version [2023b.18](https://mvnrepository.com/artifact/net.iakovlev/timeshape/2023b.18) is not present in [Maven Central](https://repo.maven.apache.org/maven2/net/iakovlev/timeshape/maven-metadata.xml) metadata file like the previous versions?

Notice that any of these works:

```groovy
// https://mvnrepository.com/artifact/net.iakovlev/timeshape
implementation group: 'net.iakovlev', name: 'timeshape', version: '2023b.18'

implementation(group: 'net.iakovlev', name: 'timeshape', version: '[2022f.15,)')
```
But this doesn't works:

```groovy
// https://mvnrepository.com/artifact/net.iakovlev/timeshape
implementation group: 'net.iakovlev', name: 'timeshape', version: '[2023b.18,)'
```

Gradle error output:

```bash
$ ./gradlew --warning-mode all classes
> Task :grouping:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grouping:compileJava'.
> Could not resolve all files for configuration ':grouping:compileClasspath'.
   > Could not find any version that matches net.iakovlev:timeshape:[2023b.18,).
     Versions that do not match:
       - 2022g.17
       - 2022g.16
       - 2022f.15
       - 2021c.14
       - 2021c.13
       - + 12 more
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/net/iakovlev/timeshape/maven-metadata.xml
     Required by:
         project : libcoordinates

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
14 actionable tasks: 1 executed, 13 up-to-date
```

**Comment by RomanIakovlev** [comment]
That's weird, I haven't seen this before. The version 2023b.18 is indeed not appearing in the https://repo1.maven.org/maven2/net/iakovlev/timeshape/maven-metadata.xml, although it's visible in the Sonatype file here: https://oss.sonatype.org/service/local/repositories/releases/content/net/iakovlev/timeshape/maven-metadata.xml.  

The actual jar files are present in the https://repo1.maven.org/maven2/net/iakovlev/timeshape/2023b.18/, so the problem seems to be only with `maven-metadata.xml`. I think it's some Sonatype -> Maven Central synchronization issue, and should be raised with Sonatype support. I don't have capacity to do this right now (mainly because they seem to have moved their support from Jira somewhere else, and I need to spend some time finding where to ask), so I'd be thankful for some help here.

**Comment by RomanIakovlev** [comment]
Just FYI @juarezr, this seem to be fixed now, all the versions appear here: https://repo1.maven.org/maven2/net/iakovlev/timeshape/maven-metadata.xml, so your Gradle build with a version range should probably work.

**Pull request merged**
